language: r
sudo: false
cache: packages

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
